### ISSUE TITLE
Array in Javascript

### ISSUE THREAD

**Issue by divyanshrastogi51** [Crio-Bytes/DSA#10]
**MicroByte Title:** Array in Javascript

**Domain:** 

- WEB

- JavaScript

**Scope of learning for learners:** 

- Basics of Array data structures

- Time Complexity of different operations  

**Activities:**  

- Insertion Operations

- Deletion Operations

- Searching Operations

**Comment by Kevinpaulose05** [comment]
Make sure you follow the proper workflow. Don't make it too lengthy(max 1hr) and also don't make it tutorialish. Give room for contributors to contribute to your repo

**Comment by divyanshrastogi51** [comment]
Okay, I will try my best. Feel free to give feedback

**Comment by Ak-Shaw** [comment]
@divyanshrastogi51 Kindly edit your issue description with the following changes in mind:

DSA is the name of the master repo, also it's like a super set. For the domain, you can add tags like **arrays**, **linear data structures**, **javascript**, etc., so kindly change that.

For **scope of learning for learners** and **activities**, you should add bullet points, like:

**Activities:**

- Activity1
- Activity2
- Activity3

Follow the same for **scope of learning for learners**. Also add a short description, like a one-liner for each bullet point, don't just casually mention them.

Following this flow with aid in thinking clearly about your project. I hope you have some direction now, so kindly incorporate the changes requested in the issue description.
