### ISSUE TITLE
Add traverse and update activites for Array in Javascript MicroByte

### ISSUE THREAD

**Issue by Ak-Shaw** [Crio-Bytes/DSA#23]
**MicroByte Title:** Array in Javascript

**Improvement Proposal:** <list out what improvements you are proposing to provide>

- Adding an activity for traversing the array, both forward and backwards
- Adding an activity for updating the array, at various indices or as a whole

**Benefits of proposed improvements:** <list out the benefits of the aforementioned improvements you want to offer>

- Would be more beginner friendly for student developers who're looking forward to learn JavaScript

**Comment by Janhavi-Gautam** [comment]
I would like to work on this issue . Could you assign me this?

**Comment by Kevinpaulose05** [comment]
> I would like to work on this issue . Could you assign me this?

Sure go right ahead. Make sure you follow a proper folder structure and also open the right PR.

Refer [this](https://github.com/Crio-Bytes/Networking/tree/main/traceroute) and [this](https://github.com/Crio-Bytes/Miscellaneous/tree/main/Building_a_Decoupled_Voice_Assistant). These are some of the right ways to do it.

All the best!
