### ISSUE TITLE
How to connect nodes at same level in a binary tree

### ISSUE THREAD

**Issue by amoghrajesh** [Crio-Bytes/DSA#25]
**MicroByte Title:** BinaryTree_LevelOrderTraversal_Types

**Improvement Proposal:** 
- Add solution to connect nodes at same level as mentioned in Further Exploration Question 2
- Implement it in any language and add briefly documented code

**Benefits of proposed improvements:** 

- The learner will be able to find a solution to the Further Exploration section too

**Comment by DivyaSaravanan** [comment]
Can I work on this Issue @amoghrajesh ?

**Comment by Ak-Shaw** [comment]
@DivyaSaravanan Sure. Go ahead. Assigning to you.

**Comment by DivyaSaravanan** [comment]
@Ak-Shaw Could you check on my PR #30
