### ISSUE TITLE
How to print clockwise spiral traversal of a binary tree

### ISSUE THREAD

**Issue by amoghrajesh** [Crio-Bytes/DSA#26]
**MicroByte Title:** BinaryTree_LevelOrderTraversal_Types

**Improvement Proposal:** 
- Add solution to clockwise spiral traversal of binary tree as mentioned in Further Exploration Question 3
- Implement it in any language and add briefly documented code

**Benefits of proposed improvements:** 

- The learner will be able to find a solution to the Further Exploration section too

**Comment by verma-pulkit** [comment]
I would like to contribute in this, please assign cpp to me.

**Comment by verma-pulkit** [comment]
I would like to contribute the code in cpp.

**Comment by Ak-Shaw** [comment]
@verma-pulkit yours now.
