### ISSUE TITLE
How to find the maximum node at a given level in a binary tree

### ISSUE THREAD

**Issue by amoghrajesh** [Crio-Bytes/DSA#27]
**MicroByte Title:** BinaryTree_LevelOrderTraversal_Types

**Improvement Proposal:** 
- Add solution to finding maximum node at a given level in a binary tree as mentioned in Further Exploration Question 4
- Implement it in any language and add briefly documented code

**Benefits of proposed improvements:** 

- The learner will be able to find a solution to the Further Exploration section too

**Comment by DivyaSaravanan** [comment]
Can I work on this @amoghrajesh

**Comment by verma-pulkit** [comment]
I want to work on this, please assign in cpp.

**Comment by Ak-Shaw** [comment]
Cool. @verma-pulkit assigning it to you.

**Comment by Ak-Shaw** [comment]
Since @DivyaSaravanan asked first, this issue is hers to work on.
