### ISSUE TITLE
Sorting Algothims

### ISSUE THREAD

**Issue by divya1509** [Crio-Bytes/DSA#31]
**MicroByte Title:** Sorting Algorithms in java

**Domain:** DSA

**Scope of learning for learners:** Understanding the working of different sorting algorithms like Bubble sort, Insertion sort, Quick sort, Merge sort, etc.

**Activities:** Learning and comparing each algorithm's space and time complexities and workflow.

**Comment by divya1509** [comment]
I would like to work on this issue @CrioDo.

**Comment by archithdwij** [comment]
@divya1509 you can start working on this. Make sure you follow learn by doing approach while creating the activites. Learn more about the contribution guidelines in contributing.md file! All the best :+1:

**Comment by Mukulbaid63** [comment]
Can i also be a part of this issue?

**Comment by Ak-Shaw** [comment]
@Mukulbaid63 Sorry, this is an idea on which @divya1509 is currently working upon. 
If you have your own idea, feel free to contribute by going through the **CONTRIBUTING.md** of our repo. Nevertheless, you are free to checkout other issues that need help.

**Comment by Ayush7-BIT** [comment]
Hey i wanna work on this issue.. please assign me this if possible..

**Comment by Kevinpaulose05** [comment]
> Hey i wanna work on this issue.. please assign me this if possible..

This issue has been solved by @divya1509 . U may try solving any issues if she has opened or try to go with something new
