### ISSUE TITLE
[C++] Data Structure 

### ISSUE THREAD

**Issue by TheShubham-K** [Crio-Bytes/DSA#48]
**MicroByte Title:** Data Structure 

**Domain:** Data Structures using C++

**Scope of learning for learners:**  Basic Algorithms and Data Structure Implementation.

**Activities:** The learner will be able to find a solution to some important Algorithms.

**Comment by amoghrajesh** [comment]
Hey @TheShubham-K !
Can you be more specific on what you will be implementing in this repo?
If you plan on doing a generic version of DS and Algo, we already have a repo for it here: https://github.com/Crio-Bytes/DSA/tree/main/Getting%20Started%20with%20DSA
You can contribute anything you like to it after raising the appropriate issues.

**Comment by Kevinpaulose05** [comment]
@TheShubham-K  Pls restructure this PR and make all changes in this PR itself. Else there will be a lot of confusion later.

**Comment by TheShubham-K** [comment]
yea sure i will all necessary changes in this PR asap
