### ISSUE TITLE
Add sorting of arrays in Javascript

### ISSUE THREAD

**Issue by Sreejan-22** [Crio-Bytes/DSA#56]
**MicroByte Title:** Array in Javascript

**Improvement Proposal:** Add ways to sort an array in javascript(along with in-built methods) and add problems related to it

**Benefits of proposed improvements:** Sorting is a very essential and common task when it comes to arrays. It is also important to
let the readers know about the in-built methods for the same so that they come in handy during regular use and save time

**Comment by anut123** [comment]
can I work on this issue?

**Comment by Sreejan-22** [comment]
Actually I created this issue so that I can work on it.

**Comment by anut123** [comment]
okay

**Comment by Ak-Shaw** [comment]
@Sreejan-22 same goes to this issue as the other one, if you wanna add code in the README.md, add it in collapsible markdown. Nevertheless, we encourage you add all your code in the src folder.

**Comment by Ak-Shaw** [comment]
@anut123 You can try to go through the other content that we have and checkout whether if you have any ideas for improvements.

**Comment by anut123** [comment]
okay sir
