### ISSUE TITLE
Methods to transform an array in Javascript

### ISSUE THREAD

**Issue by Sreejan-22** [Crio-Bytes/DSA#57]
**MicroByte Title:** Array in Javascript

**Improvement Proposal:** Add methods that transform and reorder an array and also add relevant problems.

**Benefits of proposed improvements:** These methods are necessary to solve frequently appearing problems related to arrays in Javascript.

**Comment by Ak-Shaw** [comment]
Over to you @Sreejan-22 

Points to remember though:
- README.md should not contain much of code, even if it does, it should be in collapsible markdown.
- We prefer code in the src directory.

**Comment by Sreejan-22** [comment]
Sure. Will take care of that.
