### ISSUE TITLE
String Search

### ISSUE THREAD

**Issue by IamShubhamGupto** [Crio-Bytes/DSA#9]
**MicroByte Title:** String Search

**Domain:** DSA

**Scope of learning for learners:** Understanding the working of KMP and Rabin Karp Algorithm

**Activities:** Compare performance each algorithm: Best/Average/Worst

**Comment by IamShubhamGupto** [comment]
Id like to work on this @CrioDo

**Comment by CrioDo** [comment]
+som

**Comment by amoghrajesh** [comment]
@IamShubhamGupto you can start working on it. Kindly follow the learn by doing idealogy and the contributing.md file to know more 👍🏽

**Comment by verma-pulkit** [comment]
I would like to work on this, if it is still open.

**Comment by IamShubhamGupto** [comment]
> I would like to work on this, if it is still open.

Hey, I am currently working on this. The boiler plate code is ready and i just need to generate good testcases.

**Comment by amoghrajesh** [comment]
@verma-pulkit it is already assigned.

**Comment by IamShubhamGupto** [comment]
@amoghrajesh do check out PR #50. let me know if any changes

**Comment by amoghrajesh** [comment]
Hey @IamShubhamGupto, we will review it asap. 
Also, you need to follow a template for submitting the PR as used in this PR: https://github.com/Crio-Bytes/Web/pull/6
You can find the template in the .github folder of each repo 😄.

**Comment by IamShubhamGupto** [comment]
My bad, will keep that in mind for the next PR👍

**Comment by IamShubhamGupto** [comment]
@amoghrajesh Do check it out again
I have tried sticking to PR template and made requested changes 🤞
